swagger: '2.0'
info:
  description: Remove Classification
  version: 1.0.0
  title: Remove Classification
  # put the contact info for your development or API team
  contact:
    email: xfan3@wpi.edu

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers

paths:
  /classification/remove/{classID}:
    post:
      tags:
      - developers
      summary: remove classification
      operationId: removeClassification
      description: remove classification
      produces:
      - application/json
      parameters:
      - in: path
        name: classID
        description: pass parent id
        required: true
        type: string
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Classification'
        400:
          description: bad input parameter

definitions:
  Classification:
    type: object
    required:
    - postion
    - name
    properties:
      postion:
        type: string
      name:
        type: string
        

# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
# basePath: /xfan3/GetClassification/1.0.0
# schemes:
#  - http
# Added by API Auto Mocking Plugin
schemes:
 - https
# Added by API Auto Mocking Plugin
# basePath: /WPICS503/GetClassificationHierarchy/1.0.0
# Added by API Auto Mocking Plugin
basePath: /WPICS503/RemoveClassification/1.0.0